<?php

namespace ContainerJZcxprk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMealPlanControllernewMealPlanService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.a7do2E..App\Controller\MealPlanController::newMealPlan()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a7do2E..App\\Controller\\MealPlanController::newMealPlan()'] = ($container->privates['.service_locator.a7do2E.'] ?? $container->load('get_ServiceLocator_A7do2E_Service'))->withContext('App\\Controller\\MealPlanController::newMealPlan()', $container);
    }
}
