<?php

namespace ContainerJZcxprk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMealPlanControllerupdateMealPlanService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._JFbWo0.App\Controller\MealPlanController::updateMealPlan()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._JFbWo0.App\\Controller\\MealPlanController::updateMealPlan()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mealPlanRepository' => ['privates', 'App\\Repository\\MealPlanRepository', 'getMealPlanRepositoryService', true],
            'mealRepository' => ['privates', 'App\\Repository\\MealRepository', 'getMealRepositoryService', true],
        ], [
            'entityManager' => '?',
            'mealPlanRepository' => 'App\\Repository\\MealPlanRepository',
            'mealRepository' => 'App\\Repository\\MealRepository',
        ]))->withContext('App\\Controller\\MealPlanController::updateMealPlan()', $container);
    }
}
