<?php

namespace ContainerJZcxprk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllerdeleteOrderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UJVqneq.App\Controller\OrderController::deleteOrder()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UJVqneq.App\\Controller\\OrderController::deleteOrder()'] = ($container->privates['.service_locator.UJVqneq'] ?? $container->load('get_ServiceLocator_UJVqneqService'))->withContext('App\\Controller\\OrderController::deleteOrder()', $container);
    }
}
