<?php

namespace ContainerJZcxprk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegisterControllersendVerificationEmailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UfqNAr8.App\Controller\RegisterController::sendVerificationEmail()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UfqNAr8.App\\Controller\\RegisterController::sendVerificationEmail()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'user' => ['privates', '.errored..service_locator.UfqNAr8.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.UfqNAr8": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
            'router' => ['services', 'router', 'getRouterService', false],
        ], [
            'mailer' => '?',
            'user' => 'App\\Entity\\User',
            'router' => '?',
        ]))->withContext('App\\Controller\\RegisterController::sendVerificationEmail()', $container);
    }
}
