<?php

namespace ContainerJZcxprk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerupdateDetailsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xHvYH7o.App\Controller\UserController::updateDetails()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xHvYH7o.App\\Controller\\UserController::updateDetails()'] = ($container->privates['.service_locator.xHvYH7o'] ?? $container->load('get_ServiceLocator_XHvYH7oService'))->withContext('App\\Controller\\UserController::updateDetails()', $container);
    }
}
