<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Patch;
use ApiPlatform\Metadata\Post;
use ApiPlatform\Metadata\Delete;
use App\Enum\OrderStatus;
use App\Repository\OrderRepository;
use App\State\OrderStateProcessor;
use DateTime;
use DateTimeImmutable;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ApiResource(
    operations: [
        new GetCollection(
            normalizationContext: ['groups' => ['order:read']],
        ),
        new Get(
            normalizationContext: ['groups' => ['order:read:detailed']],
            security: "is_granted('ROLE_ADMIN') or object.getCustomer() == user or object.getRestaurant().isOwnedBy(user)"
        ),
        new Post(
            denormalizationContext: ['groups' => ['order:write']],
            processor: OrderStateProcessor::class
        ),
        new Patch(
            denormalizationContext: ['groups' => ['order:update']],
            security: "is_granted('ROLE_ADMIN') or object.getRestaurant().isOwnedBy(user) or (object.getCustomer() == user and object.getStatus() == \App\Enum\OrderStatus::Unpaid)",
            // This processor will handle allowed status changes
            processor: OrderStateProcessor::class
        ),
        new Delete(
            security: "is_granted('ROLE_ADMIN') or (object.getCustomer() == user and object.getStatus() == \App\Enum\OrderStatus::Unpaid)"
        )
    ],
    // Default normalization for collections
    normalizationContext: ['groups' => ['order:read']]
)]
#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
#[ORM\Index(fields: ['status'])]
#[ORM\HasLifecycleCallbacks]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['order:read', 'order:read:detailed'])]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    #[Groups(['order:read:detailed'])] // Read-only, set by processor
    private ?User $customer = null;

    #[ORM\Column(type: 'string', enumType: OrderStatus::class)]
    #[Groups(['order:read', 'order:read:detailed', 'order:update'])] // Owners can update status
    private OrderStatus $status = OrderStatus::Unpaid;

    #[ORM\OneToMany(targetEntity: OrderItem::class, mappedBy: 'order', cascade: ['persist'], orphanRemoval: true)]
    #[Groups(['order:read:detailed', 'order:write', 'order:update'])] // Fully manageable as a nested object
    private Collection $orderItems;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    #[Groups(['order:read', 'order:read:detailed', 'order:write'])] // Set on creation
    private ?Restaurant $restaurant = null;

    #[ORM\OneToMany(targetEntity: Delivery::class, mappedBy: 'order', cascade: ['persist'], orphanRemoval: true)]
    #[Groups(['order:read:detailed'])] // Read-only, generated by the system
    private Collection $deliveries;

    #[ORM\Column]
    #[Groups(['order:read', 'order:read:detailed'])] // Read-only, set by processor
    private ?int $total = null;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    #[Groups(['order:read:detailed', 'order:write', 'order:update'])]
    private ?DateTimeInterface $deliveryStartDate = null;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    #[Groups(['order:read:detailed', 'order:write', 'order:update'])]
    private ?DateTimeInterface $deliveryEndDate = null;

    #[ORM\Column(type: 'json')]
    #[Groups(['order:read:detailed', 'order:write', 'order:update'])]
    private ?array $deliveryDays = [];

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['order:read:detailed'])] // Read-only, for customer and admins
    private ?string $paymentIntentId = null;

    public function __construct()
    {
        $this->orderItems = new ArrayCollection();
        $this->deliveries = new ArrayCollection();
    }

    // ... (All getters and setters remain the same)
    // ...

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCustomer(): ?User
    {
        return $this->customer;
    }

    public function setCustomer(?User $customer): static
    {
        $this->customer = $customer;

        return $this;
    }

    public function getStatus(): OrderStatus
    {
        return $this->status;
    }

    public function setStatus(OrderStatus $status): static
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection<int, OrderItem>
     */
    public function getOrderItems(): Collection
    {
        return $this->orderItems;
    }

    public function addOrderItem(OrderItem $orderItem): static
    {
        if (!$this->orderItems->contains($orderItem)) {
            $this->orderItems->add($orderItem);
            $orderItem->setOrder($this);
        }

        return $this;
    }

    public function removeOrderItem(OrderItem $orderItem): static
    {
        if ($this->orderItems->removeElement($orderItem)) {
            // set the owning side to null (unless already changed)
            if ($orderItem->getOrder() === $this) {
                $orderItem->setOrder(null);
            }
        }

        return $this;
    }

    public function getRestaurant(): ?Restaurant
    {
        return $this->restaurant;
    }

    public function setRestaurant(?Restaurant $restaurant): static
    {
        $this->restaurant = $restaurant;

        return $this;
    }

    /**
     * @return Collection<int, Delivery>
     */
    public function getDeliveries(): Collection
    {
        return $this->deliveries;
    }

    public function addDelivery(Delivery $delivery): static
    {
        if (!$this->deliveries->contains($delivery)) {
            $this->deliveries->add($delivery);
            $delivery->setOrder($this);
        }

        return $this;
    }

    public function removeDelivery(Delivery $delivery): static
    {
        if ($this->deliveries->removeElement($delivery)) {
            // set the owning side to null (unless already changed)
            if ($delivery->getOrder() === $this) {
                $delivery->setOrder(null);
            }
        }

        return $this;
    }

    public function getTotal(): ?int
    {
        return $this->total;
    }

    public function setTotal(int $total): static
    {
        $this->total = $total;

        return $this;
    }

    public function calculateTotal(): int
    {
        $total = 0;
        $deliveryDaysCount = 0;

        if ($this->deliveryStartDate && $this->deliveryEndDate && !empty($this->deliveryDays)) {
            $currentDate = clone $this->deliveryStartDate;
            while ($currentDate <= $this->deliveryEndDate) {
                $dayOfWeek = $currentDate->format('D'); // e.g., Mon, Tue
                if (in_array($dayOfWeek, $this->deliveryDays)) {
                    $deliveryDaysCount++;
                }
                $currentDate = $currentDate->modify('+1 day');
            }
        }

        foreach ($this->orderItems as $orderItem) {
            $mealPlan = $orderItem->getMealPlan();
            if ($mealPlan !== null) {
                $itemTotal = $mealPlan->getPrice() * $orderItem->getQuantity();
                $total += $itemTotal * $deliveryDaysCount;
            }
        }

        return $total;
    }

    public function getDeliveryStartDate(): ?DateTimeInterface
    {
        return $this->deliveryStartDate;
    }

    public function setDeliveryStartDate(?DateTimeInterface $deliveryStartDate): static
    {
        if ($deliveryStartDate instanceof DateTime) {
            $deliveryStartDate = DateTimeImmutable::createFromMutable($deliveryStartDate);
        }
        $this->deliveryStartDate = $deliveryStartDate;

        return $this;
    }

    public function getDeliveryEndDate(): ?DateTimeInterface
    {
        return $this->deliveryEndDate;
    }

    public function setDeliveryEndDate(?DateTimeInterface $deliveryEndDate): static
    {
        if ($deliveryEndDate instanceof DateTime) {
            $deliveryEndDate = DateTimeImmutable::createFromMutable($deliveryEndDate);
        }
        $this->deliveryEndDate = $deliveryEndDate;

        return $this;
    }

    public function getDeliveryDays(): ?array
    {
        return $this->deliveryDays;
    }

    public function setDeliveryDays(?array $deliveryDays): static
    {
        $this->deliveryDays = $deliveryDays;

        return $this;
    }

    public function getPaymentIntentId(): ?string
    {
        return $this->paymentIntentId;
    }

    public function setPaymentIntentId(?string $paymentIntentId): static
    {
        $this->paymentIntentId = $paymentIntentId;

        return $this;
    }
}