<?php

namespace ContainerVuPUnmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMealPlanControllergetMealPlansService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4dGOqE1.App\Controller\MealPlanController::getMealPlans()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4dGOqE1.App\\Controller\\MealPlanController::getMealPlans()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\MealPlanRepository', 'getMealPlanRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\MealPlanRepository',
        ]))->withContext('App\\Controller\\MealPlanController::getMealPlans()', $container);
    }
}
