<?php

namespace ContainerVuPUnmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllernewOrderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.a7do2E..App\Controller\OrderController::newOrder()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a7do2E..App\\Controller\\OrderController::newOrder()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mealRepository' => ['privates', 'App\\Repository\\MealRepository', 'getMealRepositoryService', true],
        ], [
            'entityManager' => '?',
            'mealRepository' => 'App\\Repository\\MealRepository',
        ]))->withContext('App\\Controller\\OrderController::newOrder()', $container);
    }
}
