<?php

namespace ContainerVuPUnmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllergetUserDetailsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zXOlprV.App\Controller\UserController::getUserDetails()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zXOlprV.App\\Controller\\UserController::getUserDetails()'] = ($container->privates['.service_locator.zXOlprV'] ?? $container->load('get_ServiceLocator_ZXOlprVService'))->withContext('App\\Controller\\UserController::getUserDetails()', $container);
    }
}
