<?php

namespace ContainerVuPUnmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.W3Uq0oo.App\Controller\UserController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.W3Uq0oo.App\\Controller\\UserController::delete()'] = ($container->privates['.service_locator.W3Uq0oo'] ?? $container->load('get_ServiceLocator_W3Uq0ooService'))->withContext('App\\Controller\\UserController::delete()', $container);
    }
}
