<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJZcxprk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJZcxprk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJZcxprk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJZcxprk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJZcxprk\App_KernelDevDebugContainer([
    'container.build_hash' => 'JZcxprk',
    'container.build_id' => 'eda5a065',
    'container.build_time' => 1738256786,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJZcxprk');
